name: onboarding_repository
description: onBoarding Repository
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_database: ^10.5.1
  firebase_core: ^2.29.0
  firebase_auth: ^4.17.9
  intl: ^0.18.0
  crypto: ^3.0.3
  encrypt: ^5.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0
