// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWk0kj0JryGLcJOsGNHKS8376-gTSgV4I',
    appId: '1:808336413203:web:cd4d808cbc66ef8f55e5e6',
    messagingSenderId: '808336413203',
    projectId: 'password-generator-cb253',
    authDomain: 'password-generator-cb253.firebaseapp.com',
    storageBucket: 'password-generator-cb253.appspot.com',
    measurementId: 'G-V28H9JGFWB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbzfkSPgyXgVALR7V106vxyfqM01FHeh0',
    appId: '1:808336413203:android:b8519377689b916255e5e6',
    messagingSenderId: '808336413203',
    projectId: 'password-generator-cb253',
    storageBucket: 'password-generator-cb253.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLqrK-9gU1twBHgjDqSPBeIBcEcsyILf4',
    appId: '1:808336413203:ios:48b115a67f84a54e55e5e6',
    messagingSenderId: '808336413203',
    projectId: 'password-generator-cb253',
    storageBucket: 'password-generator-cb253.appspot.com',
    iosBundleId: 'com.example.verygoodcore.cyberman',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLqrK-9gU1twBHgjDqSPBeIBcEcsyILf4',
    appId: '1:808336413203:ios:678dff6008fb86ca55e5e6',
    messagingSenderId: '808336413203',
    projectId: 'password-generator-cb253',
    storageBucket: 'password-generator-cb253.appspot.com',
    iosBundleId: 'com.example.myApp.RunnerTests',
  );
}
